/* DO NOT EDIT: This file is autogenerated. */
#ifdef HEADER_A7C12A92
  #error "Only include from driver CPP!"
#endif
#define HEADER_A7C12A92

#include <leos/reg.h>
typedef enum {
  LED0_Off           = 0, /* LED is off */
  LED0_On            = 1, /* LED is on */
} LED0_enum;

typedef enum {
  LED1_Off           = 0, /* LED is off */
  LED1_On            = 1, /* LED is on */
} LED1_enum;

typedef struct {
  union {
    REG32 REG;
    REG32 LED0         : 1; /* RW:  */
    REG32 LED1         : 1; /* RW:  */
  };
} _0000; /* LED */

typedef enum {
  BUTTON0_Off        = 0, /* BUTTON is off */
  BUTTON0_On         = 1, /* BUTTON is on */
} BUTTON0_enum;

typedef enum {
  BUTTON1_Off        = 0, /* BUTTON is off */
  BUTTON1_On         = 1, /* BUTTON is on */
} BUTTON1_enum;

typedef struct {
  union {
    REG32 REG;
    REG32 BUTTON0      : 1; /* RW:  */
    REG32 BUTTON1      : 1; /* RW:  */
  };
} _0008; /* BUTTON */

typedef REG32 _0010; /* CLK1HZ */
typedef REG32 _0014; /* CLK100HZ */
typedef REG32 _0018; /* COUNTER */
typedef REG32 _001C; /* PRESCALER */
typedef REG32 _0020; /* PSCNTR */
typedef struct {
  union {
    REG32 REG;
    REG32 PAD0         : 9;
    REG32 SHIELD1_SPI_nCS : 1; /* RW:  */
    REG32 SHIELD0_SPI_nCS : 1; /* RW:  */
    REG32 ADC_SPI_nCS  : 1; /* RW:  */
    REG32 CLCD_BL_CTRL : 1; /* RW:  */
    REG32 CLCD_RD      : 1; /* RW:  */
    REG32 CLCD_RS      : 1; /* RW:  */
    REG32 CLCD_RESET   : 1; /* RW:  */
    REG32 SPI_nSS      : 1; /* RW:  */
    REG32 CLCD_CS      : 1; /* RW:  */
  };
} _004C; /* MISC */


// Top-level register defs
typedef struct {
  _0000 LED;           /* RW: LED Connections */
   PAD(0x4, 0x8);
  _0008 BUTTON;        /* RW: Button Connections */
   PAD(0xc, 0x10);
  _0010 CLK1HZ;        /* RO: 1Hz Up Counter */
  _0014 CLK100HZ;      /* RO: 100Hz Up Counter */
  _0018 COUNTER;       /* RW: Cycle up counter */
  _001C PRESCALER;     /* RW: Reload value for prescaler counter */
  _0020 PSCNTR;        /* RW: Prescale Counter */
   PAD(0x24, 0x4c);
  _004C MISC;          /* RW: Misc. Control */
} reg_t;
#define PA7C12A92_FP 0xe4415242
#define PA7C12A92_SZ 80
